{% set name = "cdasws" %}
{% set version = "1.7.46" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cdasws-{{ version }}.tar.gz
  sha256: 3dfd518e7f55ba155c107880ac63c6066f4c2ac2a5663cba36c4574cdc1ec766

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-dateutil >=2.8.0
    - requests >=2.20
    - urllib3 >=1.24.1

test:
  imports:
    - cdasws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://cdaweb.gsfc.nasa.gov/WebServices/REST
  summary: NASA's Coordinated Data Analysis System Web Service Client Library
  license: NOSL
  license_file: NASA_Open_Source_Agreement_1.3.txt

extra:
  recipe-maintainers:
    - berniegsfc
